### ISSUE TITLE
[Start Here] Contribute to C-plus-plus Algorithms Library

### ISSUE THREAD

**Issue by codewithdev** [codewithdev/C-plus-plus-Algorithms#125]
** Hacktoberfest 2022 🖤✨**
------------------
We welcome you to participate in Hacktoberfest again by contributing to the "C-plus-plus-Algorithms". You can make it big by adding new contents, questions or finding any bugs. Nothing new, but you will learn more by contributing more. That's being said, there is a lot of things to learn. Happy Contributing!!

Some lists of algorithms and questions to help you in contribution:

  -  String related problems
  -  Linked List problems
  -  Binary Tree problems
  -  List of Graph Algorithms and related problems
  -  List of Dynamic Programming problems
  -  Leetcode, hackerrank, or other interview-asked problems.

Check off the list before making any PR:

 -  Read [Contribution.md](https://github.com/codewithdev/C-plus-plus-Algorithms/blob/master/CONTRIBUTING.md)
 -  Read [code of conduct](https://thoughtbot.com/open-source-code-of-conduct).
 -  Create a commit to the right category in the library.
 -  Follow the Issue template.
 
For more information check the guidelines https://hacktoberfest.com/participation/

*_Swimmingly 🦈_*

**Comment by hitaarthh** [comment]
Hey, Can i work on this issue?

**Comment by codewithdev** [comment]
> Hey, Can i work on this issue?

Ofcourse, you can!

**Comment by jak1110p0** [comment]
> ## ** Hacktoberfest 2022🖤✨**
> เรายินดีต้อนรับคุณให้เข้าร่วม Hacktoberfest อีกครั้งโดยมีส่วนร่วมใน "C-plus-plus-Algorithms" คุณสามารถทำให้มันยิ่งใหญ่ได้ด้วยการเพิ่มเนื้อหา คำถาม หรือหาจุดบกพร่องใหม่ๆ ไม่มีอะไรใหม่ แต่คุณจะได้เรียนรู้เพิ่มเติมโดยมีส่วนร่วมมากขึ้น ที่ถูกกล่าวว่ามีหลายสิ่งที่ต้องเรียนรู้ ร่วมยินดี!!
> 
> รายการอัลกอริทึมและคำถามที่จะช่วยคุณในการสนับสนุน:
> 
> * ปัญหาที่เกี่ยวข้องกับสตริง
> * ปัญหารายการเชื่อมโยง
> * ปัญหาต้นไม้ไบนารี
> * รายการอัลกอริธึมกราฟและปัญหาที่เกี่ยวข้อง
> * รายการปัญหาการเขียนโปรแกรมแบบไดนามิก
> * Leetcode, hackerrank หรือปัญหาอื่น ๆ ที่ถามถึงการสัมภาษณ์
> 
> ตรวจสอบรายชื่อก่อนทำการประชาสัมพันธ์ใดๆ:
> 
> * อ่าน[Contribution.md](https://github.com/codewithdev/C-plus-plus-Algorithms/blob/master/CONTRIBUTING.md)
> * อ่าน[จรรยาบรรณ](https://thoughtbot.com/open-source-code-of-conduct) _
> * สร้างความมุ่งมั่นในหมวดหมู่ที่ถูกต้องในไลบรารี
> * ทำตามเท็มเพลตปัญหา
> 
> สำหรับข้อมูลเพิ่มเติม ตรวจสอบแนวทางปฏิบัติhttps://hacktoberfest.com/participation/
> 
> __ว่ายน้ำเ__
https://github.com/codewithdev/C-plus-plus-Algorithms/issues/125#issue-1392779976
