### ISSUE TITLE
want to add CREATE PERMUTATION problem in C++ from DSA

### ISSUE THREAD

**Issue by rahulranjan74** [codewithdev/C-plus-plus-Algorithms#132]
PROBLEM LINK - https://www.codechef.com/LTIME112D/problems/PERMCREATE

**Comment by codewithdev** [comment]
Hey @rahulranjan74 add files within `C-plus-plus-Algorithms > ONLINE JUDGE >Codechef Problems` and raise a PR against master from your branch.

**Comment by rahulranjan74** [comment]
> Hey @rahulranjan74 add files within `C-plus-plus-Algorithms > ONLINE JUDGE >Codechef Problems` and raise a PR against master from your branch.

so i will create a new PR right ?

**Comment by rahulranjan74** [comment]
@codewithdev 
added the file as you said
created PR
please review it and assign me for hacktober 2022
Thanks !
