### ISSUE TITLE
[Hacktoberfest] Contrib for algos/datastructures/problems

### ISSUE THREAD

**Issue by codewithdev** [codewithdev/C-plus-plus-Algorithms#140]
** Hacktoberfest 2023 🖤✨**
------------------
We welcome you to participate in Hacktoberfest again by contributing to the "C-plus-plus-Algorithms". You can make it big by adding new contents, questions or finding any bugs. Nothing new, but you will learn more by contributing more. That's being said, there is a lot of things to learn. Happy Contributing!!

Some lists of algorithms and questions to help you in contribution:

  -  String related problems
  -  Linked List problems
  -  Binary Tree problems
  -  List of Graph Algorithms and related problems
  -  List of Dynamic Programming problems
  -  Leetcode, hackerrank, or other interview-asked problems.

Mark off the list before making any PR:

 -  Read [Contribution.md](https://github.com/codewithdev/C-plus-plus-Algorithms/blob/master/CONTRIBUTING.md)
 -  Read [code of conduct](https://thoughtbot.com/open-source-code-of-conduct).
 -  Create a commit to the right category in the library.
 -  Follow the Issue template.
 
For more information, check out the guidelines https://hacktoberfest.com/participation/

*_Swimmingly 🦈_*

**Comment by ishan-nahid** [comment]
!assign

**Comment by KumariAnupriya9680** [comment]
!assign

**Comment by KSHITIZ-RAJ-22** [comment]
I want to contribute to this repo.

**Comment by sonicdashh** [comment]
Please assign me this issue . I'd like to work on this. 
@codewithdev

**Comment by Amisha328** [comment]
Hi @codewithdev,

Please review and accept the PR #146.

Thank you !! :)

**Comment by ishan-nahid** [comment]
assign and if is it possible i upload codeforces problem solution?

**Comment by codewithdev** [comment]
> assign and if is it possible i upload codeforces problem solution?

@ishan-nahid feel free to check out the repo and raise a PR for the appropriate section.

**Comment by codewithdev** [comment]
> Please assign me this issue . I'd like to work on this. @codewithdev

feel free to check out the repo and raise a PR for the appropriate section.

**Comment by sonicdashh** [comment]
@codewithdev 
Please review and merge PR #145 .

**Comment by ishan-nahid** [comment]
@codewithdev  please review and marge the code and remember to add hacktoberfest-accepted label.

**Comment by ishan-nahid** [comment]
@codewithdev please review and marge the code and remember to add hacktoberfest-accepted label.

**Comment by ishan-nahid** [comment]
@codewithdev 
Please review and merge PR https://github.com/codewithdev/C-plus-plus-Algorithms/pull/149 .
It has been a while since I raised the PR.

**Comment by ishan-nahid** [comment]
@codewithdev what's wrong?
