### ISSUE TITLE
Add more algorithm that doesn't contain in the repo 

### ISSUE THREAD

**Issue by codewithdev** [codewithdev/C-plus-plus-Algorithms#2]
Add Your Algorithms on CPP. That do not Contains in the Repo

**Comment by DS-73** [comment]
I can add few more important algorithms. 

Please assign this issue to me

**Comment by codewithdev** [comment]
Everyone is welcome. !!

**Comment by shubhangi-singh21** [comment]
@codewithdev I would like to add some problems in dynamic programming section if you permit!

**Comment by codewithdev** [comment]
@shubhangi-singh21 Welcome! Please read the PR template to avoid adding redundant content.

**Comment by souvickroy02** [comment]
I would like to contribute more algorithms in this repo. so please allow me to work with this issue. Thank you.

**Comment by Mayukh-1999** [comment]
I want to work on this issue by adding more algorithms in this repo. Please assign me this issue.

**Comment by NishthaThakural** [comment]
I would like to work on the issue, can you please assign it to me?
