### ISSUE TITLE
[Start Here]- Push new algorithms to C-plus-plus library

### ISSUE THREAD

**Issue by codewithdev** [codewithdev/C-plus-plus-Algorithms#99]

**Comment by Sayak-0512** [comment]
Hey @codewithdev! I want to work on this issue. Can you assign me?

**Comment by codewithdev** [comment]
@Sayak-0512 Sure, you can create a PR against the repo that you want to contribute. 🙏🏼✨

**Comment by Sayak-0512** [comment]
@codewithdev Can I know how many new questions are you expecting?Can you give me  an approximate number?

**Comment by Sayak-0512** [comment]
I have created the pull request. Please review and merge.

**Comment by jineshparakh** [comment]
I have created a pull request  #102 . Please review and merge it.
Please do let me know if I need to make any changes!
